import React from 'react';

const About = () => {
    return (
        <div className="container my-5">
            <h3>Lorem, ipsum dolor.</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed, quos qui? Quidem repellendus beatae numquam reprehenderit! Delectus aspernatur dicta rerum facilis impedit quae cum neque error aperiam commodi sint, nesciunt, sed optio deserunt aut distinctio minus numquam assumenda temporibus pariatur in et sunt mollitia? Rerum voluptate quaerat aliquid sed ducimus quas nostrum sapiente alias similique. Exercitationem odit id voluptatibus sint in aperiam quo, facere delectus repudiandae laborum optio voluptates ipsa, a, atque minus pariatur cum officiis necessitatibus. Odio optio labore id odit sunt quaerat repellendus itaque illo iste omnis nihil distinctio esse sint consequuntur quibusdam nemo, molestias qui nostrum deleniti enim commodi ipsam explicabo molestiae possimus. At quia dicta tempora animi possimus, fuga maiores, dolorum exercitationem vero corrupti nulla porro. Sed saepe architecto officia consequuntur! Sed repellendus obcaecati quis ab reprehenderit. Voluptate quam blanditiis deleniti vero dolores odit voluptatem, consequuntur, nobis alias recusandae incidunt nam. Cupiditate eaque aperiam magni quod enim animi maiores id quidem dignissimos consequuntur qui soluta dicta vitae maxime asperiores, consectetur exercitationem, alias et recusandae natus ut. Fugit eius ducimus repudiandae earum similique error quo, quos, molestiae tempore velit, assumenda consectetur doloremque rem laboriosam voluptates eligendi ab aliquid magni voluptate inventore facere? Amet, ut ipsum vel blanditiis laboriosam eaque placeat officia eius adipisci vero non cumque autem minus reprehenderit! Deleniti molestias illo, consectetur earum totam perspiciatis cum?</p>
            <h3>Lorem, ipsum.</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis aliquid esse laborum quia totam sapiente maiores! Quaerat commodi autem deserunt hic labore rem quam, id est animi nulla nemo quia ea voluptate tenetur, pariatur laborum reprehenderit quisquam optio obcaecati beatae saepe. Quasi non eius magni commodi vel, libero illum, nobis sapiente asperiores, ducimus magnam? Esse consequatur libero nulla quibusdam laboriosam dolore veritatis accusamus dolor? Ullam odio cupiditate, excepturi natus in veniam, eius obcaecati corrupti eligendi doloribus atque ex aspernatur magnam dolor ab quae minus a ipsa quos laborum error qui consectetur? Debitis nisi eligendi impedit ex maxime possimus soluta, itaque distinctio reprehenderit temporibus blanditiis quis. Quia provident aspernatur harum dolores, neque nesciunt consequatur natus itaque magnam eveniet impedit dolorem. Maxime natus harum at incidunt consequuntur exercitationem, eaque soluta maiores quaerat perferendis rerum est ipsum voluptas illum aut. Nostrum reprehenderit alias cupiditate. Dolores, tempore magni. Voluptatum rem ex dignissimos dolor inventore?</p>
            <h3>Lorem ipsum dolor sit.</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus distinctio ipsa, quia veritatis soluta quasi facere excepturi voluptate molestiae nemo labore omnis quo id tempora debitis ullam non exercitationem iste repellat magni! Nihil rerum quidem quo sapiente, possimus deserunt cum quia. Consequuntur, eaque, minus explicabo nostrum ducimus, similique magni impedit dolorum veritatis porro perferendis harum id dicta officiis quae maiores quasi obcaecati voluptates! Repellat fugiat quo iste, voluptate illo alias ipsum porro voluptatum repellendus iusto esse tempore tenetur minima architecto!</p>
        </div>
    );
};

export default About;